version: "3"
services:
  # Servicio para la base de datos (PostgreSQL)
  db:
    image: postgres:16.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: zona_de_poder_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Servicio para PgAdmin
  pdAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 8180:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json

  # Servicio para tu aplicación Node.js
  app:
    build: .
    container_name: zona_de_poder_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=master
      - DB_PASSWORD=123456
      - DB_NAME=zona_de_poder_db
    volumes:
      - .:/app
volumes:
  db_data:
